### PR TITLE
WakeLocks: improve confusing user guidance in English & German.

### PR DESCRIPTION
**Pull request by spezi77**
Signed-off-by: spezi77 spezi77@gmx.com

### CODE REVIEW

**Comment by JoeSchubert** [comment]
Do you think it would be less confusing to add the current state to the description card?

**Comment by spezi77** [comment]
Hum, good point. Let's give it a try. Using a list with two state items could lead to a much clearer understanding. E.g.: allowed / blocked.

What do you think?

**Comment by JoeSchubert** [comment]
It might be.  I did something similar for a few of the toggles. It seems
like there can't be any confusion that way

**Comment by shmuelr** [comment]
Yah, I think there is a google post somewhere about have informative settings toggles that reflect the state of the toggle

**Comment by spezi77** [comment]
Alright, guys. Looking forward to seeing the wakelock toggles improved.. Let's close this one.

**Comment by JoeSchubert** [comment]
I know you closed this already... but could you check to make sure that this works more as you intended?

https://github.com/yoinx/kernel_adiutor/commit/04ddaadfaeef477fb9feda4b182102adb68957f4

**Pull request closed without merging**
