### PR TITLE
dt2w: add native support for armani

### PR DESCRIPTION
**Pull request by hemantbeast**
- Redmi 1s DT2W support

Signed-off-by: hemantbeast hemantbeast@gmail.com

### CODE REVIEW

**Comment by hemantbeast** [comment]
@yoinx  

Please add this dt2w native support for Redmi 1s (armani).

**Comment by JoeSchubert** [comment]
Sorry for the late reply.... I've been really busy in real life... 

Just adding this value to the constants doesn't really do anything. You have to actually call it from the appropriate spots.

What are the appropriate values for this? What do they do?

**Comment by hemantbeast** [comment]
This is to support the DT2W for ft5x06 display driver. Its just get the Enable/Disable control of DT2W. It is working fine with the Redmi 1s device.

And sorry for my bad english. I hope you understand what I'm saying.

**Comment by JoeSchubert** [comment]
I get that the path might be right...  But just adding it to the constants file like that doesn't do anything.

**Review by huune — APPROVED** [review]

**Comment by huune** [comment]
Comment on pull request

**Comment by huune** [comment]
Comment on pull request

**Comment by JoeSchubert** [comment]
This will not function as submitted.

**Pull request closed without merging**
