### PR TITLE
Fixed german translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Bender80** [comment]
Can't get why there is always line 904 added and it doesn't end with </resources>.

**Comment by ghost** [comment]
Sorry for all the failed checks. Can't get why the end-tag doesn't match. I can't see clearly after reading all that lines. Presumably it's a dumb error by me.

**Comment by shmuelr** [comment]
Hey, have you seen this https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling ? 

The build is failing b/c of some characters that aren't escaped

**Comment by ghost** [comment]
Ok, thanks. I think i found the problem.
"If you have a double-quote in your string, you must escape it (\"). Surrounding the string with single-quotes does not work. "

But i just read Yoinx post on Xda. Sorry to hear. But understandable. Xda is getting worse and worse. Thanks for your work.

**Comment by shmuelr** [comment]
Oh shit.. hadn't seen that post. I'm sorry it came to that.
Yah, I'll do what I can to maintain this.

In your pr look for double and single quotes. Both need to be escaped.

**Comment by ghost** [comment]
I need a rest now. Will check all lines tomorrow or so.
It was intended as a thank you to Yoinx for a feature request i made. The community takes and gives. Sadly, there are too many idiots and thankless people on xda who ruin everything.

**Comment by JoeSchubert** [comment]
yeah, I had changed my mind about discontinuing since I got immediate feedback for support to keep it going. It just gets old sometimes with deployed connectivity because it takes a lot of time to get sites to load... just to read people being too lazy to even understand what they're looking at, much less contribute to development.

**Comment by JoeSchubert** [comment]
@Bender80 , the failing part of that last PR is here:
line 370: 
`<string name="thermal_franco_stage_one_summary">Ausgelöst bei:</string>`
should probably be 

`<string name="thermal_franco_stage_one_summary">Ausgelöst bei\:</string>`

I believe that the ":" needs to be escaped.

**Comment by ghost** [comment]
I don't know. In original file https://github.com/yoinx/kernel_adiutor/blob/master/app/src/main/res/values-de/strings.xml ":" aren't escaped.
f.e.
<string name="startup_commands_list">Liste von Neustart Befehlen:</string>
Still failed. I lose my mind.

**Comment by shmuelr** [comment]
" , ', and \ need to be escaped

**Comment by ghost** [comment]
Yes.
All single and double quotes are escaped.

**Comment by shmuelr** [comment]
OK, I can take a look at this tonight on my home computer.

**Comment by JoeSchubert** [comment]
Yeah, I was just going off the Travis-CI build error since I can't pull this until I get somewhere with open internet access for my laptop.

**Comment by shmuelr** [comment]
Line 345 has an extra closing `</string>` tag

**Comment by ghost** [comment]
Finally. Thank you so much shmuelr.
As i said before. Dumb user error by me.

**Comment by shmuelr** [comment]
No worries. Thanks for contributing!

**Pull request merged**
