### PR TITLE
CPU Hotplugs: add Lazyplug.

### PR DESCRIPTION
**Pull request by spezi77**
Signed-off-by: spezi77 spezi77@gmx.com

### CODE REVIEW

**Comment by JoeSchubert** [comment]
This looks good. 

I'll try to merge it once I get normal internet as I also added support for StateHelper. If I merge this blindly I'm not sure how it will play with my offline addition for that hotplug.

**Comment by spezi77** [comment]
Altering the tunables seems to work as expected. But my problem is that I couldn't conduct extensive tests, as currently lazyplug does not work stable in my device (mako).

**Comment by JoeSchubert** [comment]
Honestly, as long as the sysfs files are changing/reading correctly & as expected that's all the testing that's really needed.

The only thing that looks like it's missing is that you left out calling the togglehotplugs function (and adding lazyplug as an option in there). That function just serves to force all other hotplugs off when turning one on. Not a big deal, when I get the chance to add this, I'll fix that if you don't before then.

**Comment by JoeSchubert** [comment]
Yeah, I was right... It didn't like my changes :( 
fixed it up though.

**Comment by spezi77** [comment]
Thanks a bunch! Btw, do you have plans to add lazyplug into Singularity kernel?

**Comment by JoeSchubert** [comment]
I don't have anything to do with the kernel anymore,  that's pelt
apophis9283 now

**Pull request merged**
