### PR TITLE
Add MSM USB OTG Hack control toggle.

### PR DESCRIPTION
**Pull request by spezi77**
Signed-off-by: spezi77 spezi77@gmx.com

### CODE REVIEW

**Comment by spezi77** [comment]
@yoinx please consider merge this new control toggle. I have received a positive test result: http://forum.xda-developers.com/showpost.php?p=66846629&postcount=515

**Comment by JoeSchubert** [comment]
Sounds good, I won't be able to merge it though until sometime later in the week.

Seems like this should go in the battery/power fragment though rather than Misc. No?
I had moved a bunch of stuff out of the Misc tab a while back because it was getting a bit too cluttered.

**Comment by spezi77** [comment]
Honestly, I really liked the Misc tab because it has not too much in common with Battery.

About USB OTG Hack. It is technically a "usb host mode". Enabling it allows the phone to act as a USB host, so that you can use other USB devices attached to it.

**Comment by JoeSchubert** [comment]
Fair enough. I'm just trying to not overload too much into one tab or another. 

I'll pull this in once I have regular internet again. Should be within the next week. I try to avoid pulling too much while I have might have unpushed changes on my laptop. Don't want you to think I'm ignoring it or anything. Thanks for the PR :)

Pretty neat hack though.

**Comment by spezi77** [comment]
Thanks for your reply. Highly appreciated! :D

Take your time..

**Pull request merged**
