### PR TITLE
Support for dyn_hotplug by Stratosk.

### PR DESCRIPTION
**Pull request by spezi77**

### CODE REVIEW

**Comment by JoeSchubert** [comment]
Thanks or doing this.

**Comment by spezi77** [comment]
I have discovered a "strange" behavior in turning on/off dyn_hotplug. It seems that reading the values in /sys/module/dyn_hotplug/parameters/enabled will always return Y or N.
While writing the values you can submit either Y/N or 1/0.

Do you have a clue if this behavior is fine and to be expected?

I did a few tests to figure this out..

root@:/ # echo 1 > /sys/module/dyn_hotplug/parameters/enabled
root@:/ # cat /sys/module/dyn_hotplug/parameters/enabled  
Y
root@:/ # echo N > /sys/module/dyn_hotplug/parameters/enabled  
root@:/ # cat /sys/module/dyn_hotplug/parameters/enabled  
N
root@:/ # echo 0 > /sys/module/dyn_hotplug/parameters/enabled  
root@:/ # cat /sys/module/dyn_hotplug/parameters/enabled  
N
root@:/ # echo 1 > /sys/module/dyn_hotplug/parameters/enabled  
root@:/ # cat /sys/module/dyn_hotplug/parameters/enabled  
Y
root@:/ # echo 0 > /sys/module/dyn_hotplug/parameters/enabled  
root@:/ # cat /sys/module/dyn_hotplug/parameters/enabled  
N
root@:/ # echo Y > /sys/module/dyn_hotplug/parameters/enabled  
root@:/ # cat /sys/module/dyn_hotplug/parameters/enabled  
Y

**Comment by JoeSchubert** [comment]
Yeah,  this is normal behavior of the module_param kernel function.

The only time that you _have_ to echo the same type of value to the node is
when people are handling the sysfs node transactions themselves rather than
utilizing the functions built into the kernel to do it.

**Comment by spezi77** [comment]
Ah ok. Thanks for clearing up. I assume that my implementation is correct, using Y/N for read & write operation?

**Comment by JoeSchubert** [comment]
Yeah,  it's always safest to match the write operation to the read.

I'm not sure if you watch my other commits,  but this is why I added that
isLetter utility function.  This can be used inline with a read in order to
match the write to the read dynamically.

I've done a few commits like that now.

**Pull request merged**
